// Inspect the actual saved automatic H1 run. No run creation or model calls.
import {chromium} from '../../frontend/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const base=process.env.SAFE_HARBOR_UI_URL??'http://127.0.0.1:5176';
const experimentId='experiment-a879d0fa4f5e499b89a43ed8b7f7f400';
const runId=process.env.SAFE_HARBOR_RUN_ID??'run-5134783b07da40f2b6ac5c6b053bf901';
const output=process.env.SAFE_HARBOR_H1_GRAPH_OUTPUT??'artifacts/safe_harbor/automatic-h1-graph/actual';
const get=async path=>{const response=await fetch(`${base}/api${path}`);assert.ok(response.ok);return response.json();};
const experiment=await get(`/experiments/${experimentId}`),snapshot=await get(`/runs/${runId}/snapshot`);
assert.equal(snapshot.run.mode,'real_model');assert.equal(snapshot.run.harness_hash,experiment.optimizer.candidate_hash);
assert.equal(snapshot.tasks.length,7);
const roles=Object.fromEntries(snapshot.tasks.map(task=>[task.role_id,task]));
assert.ok(roles.evidence_review.depends_on.includes(roles.inspect_evidence.task_id));
assert.ok(roles.compare.depends_on.includes(roles.evidence_review.task_id));
const candidate=snapshot.candidates[0],reference=snapshot.artifacts.find(a=>a.kind==='reference_assets'&&a.data.candidate_id===candidate.candidate_id);
assert.ok(reference);assert.equal(reference.data.data_version,snapshot.run.data_version);
await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1600,height:1000}}),errors=[],writes=[];
page.on('pageerror',error=>errors.push(error.message));page.on('request',request=>{if(!['GET','HEAD'].includes(request.method()))writes.push(request.method()+' '+request.url());});
try{
  await page.goto(`${base}/?run=${runId}`);
  await page.locator('.mode-word').getByText('REAL MODEL',{exact:true}).waitFor();
  await page.locator(`.react-flow__node[data-id="${roles.evidence_review.task_id}"]`).waitFor();
  assert.equal(await page.locator('.react-flow__node-task').count(),7);
  assert.equal(await page.locator('.data-version').textContent(),snapshot.run.data_version);
  assert.ok((await page.locator('.coordinate-footer').textContent()).includes(`[${candidate.start}, ${candidate.end})`));
  assert.match(await page.locator('.reference-availability').textContent(),/Frozen run assets/);
  const positions=()=>page.locator('.react-flow__node-task').evaluateAll(nodes=>Object.fromEntries(nodes.map(node=>{const [x,y]=node.style.transform.match(/translate\(([-.\d]+)px, ([-.\d]+)px\)/).slice(1).map(Number);return[node.dataset.id,{x,y}];})));
  const before=await positions();
  for(const task of snapshot.tasks)for(const parent of task.depends_on)assert.ok(before[parent].x<before[task.task_id].x,`${parent} must precede ${task.task_id}`);
  const dependencyCount=snapshot.tasks.reduce((sum,task)=>sum+task.depends_on.length,0);
  assert.equal(await page.locator('.react-flow__edge').count(),dependencyCount);
  await page.waitForTimeout(1300);assert.deepEqual(await positions(),before);
  const graph=page.getByRole('region',{name:'Investigation graph'});
  await graph.screenshot({path:`${output}/seven-task-dependencies.png`});
  await page.locator(`.react-flow__node[data-id="${roles.evidence_review.task_id}"]`).click();
  const inspector=page.getByRole('dialog',{name:'Evidence inspection'});
  await inspector.getByRole('button',{name:'Task & dependencies',exact:true}).click();
  assert.ok((await inspector.locator('.detail-list').textContent()).includes('evidence_review'));
  await inspector.getByText('Exact saved task',{exact:true}).click();
  const inspected=JSON.parse(await inspector.locator('.raw-record[open] pre').textContent());
  assert.equal(inspected.task_id,roles.evidence_review.task_id);assert.deepEqual(inspected.depends_on,roles.evidence_review.depends_on);
  assert.equal(inspected.harness_hash,experiment.optimizer.candidate_hash);
  await page.screenshot({path:`${output}/actual-reviewer-task.png`});
  await inspector.getByRole('button',{name:'Close evidence inspector'}).click();
  await page.getByRole('button',{name:/Harness evolution/}).click();
  const drawer=page.getByRole('dialog',{name:'Harness evolution'});
  await drawer.getByRole('textbox',{name:'Saved experiment ID'}).fill(experimentId);
  await drawer.getByRole('button',{name:'Open',exact:true}).click();
  const proposal=drawer.getByRole('region',{name:'Live harness proposal'});await proposal.waitFor();
  await proposal.getByText('H1 run recorded — inspect its execution',{exact:true}).waitFor();
  const link=proposal.locator(`a[href="/?run=${runId}"]`);assert.equal(await link.count(),1);
  assert.equal(await link.textContent(),'Inspect H1 run ↗');
  await proposal.scrollIntoViewIfNeeded();await page.screenshot({path:`${output}/saved-proposal-with-h1-run.png`});
  const after=await get(`/runs/${runId}/snapshot`),review=after.tasks.find(task=>task.role_id==='evidence_review');
  const traces=after.artifacts.filter(a=>a.provenance?.role_id==='evidence_review'&&['worker_trace','worker_failure_trace'].includes(a.kind));
  assert.equal(review.status,'complete');assert.ok(traces.some(trace=>trace.data.provider_responses?.length>0));
  const executedTools=traces.flatMap(trace=>(trace.data.tool_calls??[]).map(call=>call.tool_name));
  assert.ok(review.allowed_tools.includes('control_overlap'));assert.ok(!roles.compare.allowed_tools.includes('control_overlap'));
  assert.deepEqual(errors,[]);assert.deepEqual(writes,[]);
  const report={passed:true,mode:'read_only_actual_real_model_H1',experiment_id:experimentId,run_id:runId,harness_hash:snapshot.run.harness_hash,observed_run_status:after.run.status,through_sequence:after.through_sequence,data_version:snapshot.run.data_version,candidate_interval:{candidate_id:candidate.candidate_id,chromosome:candidate.chromosome,start:candidate.start,end:candidate.end,coordinate_system:candidate.coordinate_system},task_count:7,dependency_edge_count:dependencyCount,all_dependency_edges_left_to_right:true,positions_stable_across_poll:true,positions:before,task_dependencies:snapshot.tasks.map(task=>({task_id:task.task_id,role_id:task.role_id,depends_on:task.depends_on})),inserted_reviewer:{task_id:review.task_id,status:review.status,attempt:review.attempt,allowed_tools:review.allowed_tools,observed_tool_calls:executedTools,context_policy:review.context_policy,trace_artifact_ids:traces.map(a=>a.artifact_id),recorded_provider_responses:traces.reduce((n,a)=>n+(a.data.provider_responses?.length??0),0)},actual_h1_link_present:true,observed_promotion_status:experiment.promotion?.status??null,model_calls_by_inspection:0,ledger_writes:0,browser_errors:errors,limitations:['Real H1 task creation and dependency layout are verified. Reviewer execution status and available provider traces are stated at the observed watermark.','No correctness, promotion, cost win or final comparison is inferred from the graph.','The run may continue while this read-only inspection is performed.']};
  await writeFile(`${output}/report.json`,JSON.stringify(report,null,2)+'\n');
  await writeFile(`${output}/observed-run.json`,JSON.stringify(after,null,2)+'\n');
  console.log(JSON.stringify({passed:true,run_id:runId,tasks:7,reviewer:report.inserted_reviewer,report:`${output}/report.json`}));
}catch(error){await page.screenshot({path:`${output}/failure.png`}).catch(()=>{});await writeFile(`${output}/report.json`,JSON.stringify({passed:false,run_id:runId,error:String(error.stack??error),errors,writes},null,2)+'\n');throw error;}finally{await browser.close();}
