// Read-only browser journey over a saved genuine H1; no run creation or paid calls.
import {chromium} from '../../frontend/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {mkdir, readFile, writeFile} from 'node:fs/promises';

const base = process.env.SAFE_HARBOR_UI_URL ?? 'http://127.0.0.1:5176';
const runId = 'run-5134783b07da40f2b6ac5c6b053bf901';
const experimentId = 'experiment-a879d0fa4f5e499b89a43ed8b7f7f400';
const output = 'artifacts/safe_harbor/automatic-h1-replay';
const get = async path => {const response=await fetch(`${base}/api${path}`); assert.ok(response.ok); return response.json();};
const before=await get(`/runs/${runId}/export`), snapshot=before.snapshot;
const experiment=await get(`/experiments/${experimentId}`);
assert.equal(snapshot.run.mode,'real_model'); assert.equal(snapshot.run.status,'complete');
assert.equal(snapshot.run.harness_hash,experiment.optimizer.candidate_hash);
assert.equal(snapshot.tasks.length,7); assert.equal(snapshot.through_sequence,32);
const candidate=snapshot.candidates[0], assessments=[...snapshot.assessments].sort((a,b)=>a.assessment_revision-b.assessment_revision);
const [first, intermediate, latest]=assessments;
assert.deepEqual(assessments.map(a=>a.model_proposal_accepted),[false,true,false]);
const firstSequence=before.events.find(e=>e.upserts.assessments?.some(a=>a.assessment_id===first.assessment_id)).sequence;
const acceptedSequence=before.events.find(e=>e.upserts.assessments?.some(a=>a.assessment_id===intermediate.assessment_id)).sequence;
const latestSequence=before.events.find(e=>e.upserts.assessments?.some(a=>a.assessment_id===latest.assessment_id)).sequence;
assert.deepEqual([firstSequence,acceptedSequence,latestSequence],[15,23,27]);
const reference=snapshot.artifacts.find(a=>a.kind==='reference_assets'&&a.data.candidate_id===candidate.candidate_id);
const {sequence:seq,annotation}=reference.data.reference_assets;
assert.equal(createHash('sha256').update(seq.sequence).digest('hex'),seq.sha256);
assert.equal(seq.sequence.length,seq.end-seq.start);
const catalog=await get('/catalog'), chromosomeLength=catalog.chromosomes.find(c=>c.chromosome===candidate.chromosome).length;
const review=snapshot.tasks.find(t=>t.role_id==='evidence_review');
const checks=[],errors=[],writes=[];
const pass=(check,details={})=>checks.push({check,passed:true,...details});
const near=(a,b)=>assert.ok(Math.abs(a-b)<0.000001,`${a} != ${b}`);
await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1280,height:720},reducedMotion:'reduce'});
page.on('pageerror',error=>errors.push(error.message));
page.on('request',request=>{if(!['GET','HEAD'].includes(request.method()))writes.push(`${request.method()} ${request.url()}`);});
const zoom=page.getByRole('navigation',{name:'Genome zoom'}),genome=page.getByRole('region',{name:'Genome viewer'});
const slider=page.getByRole('slider',{name:'Replay event position'});
const dossier=page.getByRole('dialog',{name:`Run ${runId}`});
const seek=async sequence=>{await slider.fill(String(sequence));await page.waitForFunction(seq=>document.querySelector('.sequence-count')?.textContent===`${seq} / 32`,sequence);};
const shot=async name=>{await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:`${output}/${name}.png`});};
const closeDossier=()=>dossier.getByRole('button',{name:'Close dossier',exact:true}).last().click();
try {
  await page.goto(`${base}/?run=${runId}`);
  await page.locator('.mode-word').getByText('REAL MODEL',{exact:true}).waitFor();
  assert.equal(await page.locator('.conclusion-text').textContent(),latest.conclusion);
  await page.getByRole('combobox',{name:'Investigation execution mode'}).selectOption('real_model');
  await page.getByRole('button',{name:'Presentation',exact:true}).click();
  await page.locator('.shp-preload.ready').waitFor();
  await page.getByRole('button',{name:'Reset presentation to start'}).click();
  assert.equal(await page.locator('.mode-word').textContent(),'CATALOG PREVIEW');
  assert.equal(await page.getByRole('button',{name:'Dossier at this commit',exact:true}).isDisabled(),true);
  await page.getByRole('checkbox',{name:'Follow camera'}).uncheck();
  await seek(1);
  await page.getByRole('button',{name:'Expand task graph',exact:true}).click();
  assert.equal(await page.locator('.react-flow__node-task').count(),7);
  assert.equal(await page.locator('.react-flow__node-task .task-state.queued').count(),7);
  assert.equal(await page.locator('.at-agent.queued').count(),7);
  assert.equal(await page.locator('.at-call').count(),0);
  const treeIds=await page.locator('.at-agent').evaluateAll(nodes=>nodes.map(node=>node.dataset.treeId.slice(2)));
  for(const task of snapshot.tasks)for(const parent of task.depends_on)assert.ok(treeIds.indexOf(parent)<treeIds.indexOf(task.task_id));
  assert.equal(await page.locator('.data-version').textContent(),snapshot.run.data_version);
  assert.match(await genome.locator('.reference-availability').textContent(),/Frozen run assets/);
  pass('Reset starts before evidence; event 1 reconstructs seven queued real H1 tasks');
  await zoom.getByRole('button',{name:'Genome',exact:true}).click();
  const marker=genome.getByRole('button',{name:`Select ${candidate.name}`});
  const pos=await marker.evaluate(node=>{const bar=node.parentElement.querySelector('rect'),dot=node.querySelector('circle');return{x:+bar.getAttribute('x'),w:+bar.getAttribute('width'),cx:+dot.getAttribute('cx')};});
  near((pos.cx-pos.x)/pos.w,candidate.start/chromosomeLength);
  await zoom.getByRole('button',{name:candidate.chromosome,exact:true}).click();
  const x=await genome.locator('g.marker line').evaluate(line=>+line.getAttribute('x1'));
  near((x-35)/860,candidate.start/chromosomeLength);
  await zoom.getByRole('button',{name:'Locus',exact:true}).click();
  const names=new Set(annotation.features.flatMap(f=>[f.name,f.gene_id]).filter(Boolean));
  for(const name of await genome.locator('.svg-gene').allTextContents())assert.ok(names.has(name.replace(/ [←→]$/,'')));
  assert.ok((await genome.locator('.coordinate-footer').textContent()).includes(`[${candidate.start}, ${candidate.end})`));
  await zoom.getByRole('button',{name:'Sequence',exact:true}).click();
  const stripStart=candidate.start-20;
  const strip=await genome.locator('.sequence-row code').evaluateAll(rows=>rows.flatMap(row=>[...row.children].map(span=>({base:span.textContent,title:span.getAttribute('title')}))));
  assert.equal(strip.map(x=>x.base).join(''),seq.sequence.slice(stripStart-seq.start,stripStart-seq.start+100).toUpperCase());
  strip.forEach((base,i)=>assert.equal(base.title,`${candidate.chromosome}:${(stripStart+i+1).toLocaleString('en-US')}`));
  pass('All four zooms preserve actual Olonne-18 position, frozen annotations and exact bases',{sequence_sha256:seq.sha256,reference_artifact_id:reference.artifact_id});
  await genome.screenshot({path:`${output}/01-frozen-reference-bases.png`});
  await seek(15);
  await page.locator(`.react-flow__node[data-id="${review.task_id}"]`).click();
  const inspector=page.getByRole('dialog',{name:'Evidence inspection'});
  await inspector.getByRole('button',{name:'Task & dependencies',exact:true}).click();
  await inspector.getByText('Exact saved task',{exact:true}).click();
  const task=JSON.parse(await inspector.locator('.raw-record[open] pre').textContent());
  assert.equal(task.status,'complete');assert.deepEqual(task.depends_on,review.depends_on);
  assert.equal(task.harness_hash,snapshot.run.harness_hash);
  await inspector.getByRole('button',{name:'Close evidence inspector'}).click();
  assert.equal(await page.locator('.conclusion-text').textContent(),first.conclusion);
  pass('Event 15 exposes the executed inserted reviewer and its actual schema failure');
  const tree=page.getByRole('region',{name:'Agent tree'});
  await tree.getByRole('button',{name:'Expand all',exact:true}).click();
  const treeReview=page.locator(`[data-tree-id="a:${review.task_id}"]`);
  const reviewCalls=await treeReview.locator('..').locator('.at-call strong').allTextContents();
  assert.deepEqual(reviewCalls,['Model call 1','control overlap','retrieve evidence','Model call 2']);
  const compareTask=snapshot.tasks.find(t=>t.role_id==='compare');
  assert.ok((await page.locator(`[data-tree-id="a:${compareTask.task_id}"] .at-dep`).textContent()).includes('[evidence_review]'));
  const reviewTrace=snapshot.artifacts.find(a=>a.kind==='worker_trace'&&a.provenance.task_id===review.task_id);
  assert.ok((await treeReview.textContent()).includes(`$${reviewTrace.data.usage.cost_usd.toFixed(5)}`));
  await tree.getByRole('button',{name:'Collapse calls',exact:true}).click();
  await tree.screenshot({path:`${output}/dependency-ordered-agent-tree.png`});
  pass('Agent tree orders actual dependencies and links tools to their requesting provider response',{review_call_order:reviewCalls,review_trace_cost_usd:reviewTrace.data.usage.cost_usd});
  await seek(acceptedSequence);
  assert.equal(await page.locator('.conclusion-text').textContent(),intermediate.conclusion);
  assert.equal((await page.locator('.conclusion-panel .panel-head .pill').textContent()).trim(),'Revision 2');
  await page.getByRole('button',{name:'Dossier at this commit',exact:true}).click();
  assert.match(await dossier.locator('.shp-assessments').textContent(),/revision 2/);
  assert.equal(await dossier.locator('.shp-checks .bad').count(),0);
  const downloading=page.waitForEvent('download');
  await dossier.getByRole('button',{name:'Download dossier JSON ↓',exact:true}).click();
  const download=await downloading,historical=JSON.parse(await readFile(await download.path(),'utf8'));
  assert.equal(historical.snapshot.through_sequence,23);
  assert.deepEqual(historical.immutable_assessment_revisions.map(a=>a.assessment_revision).sort(),[1,2]);
  assert.ok(historical.events.every(e=>e.sequence<=23));
  assert.ok(!historical.snapshot.assessments.some(a=>a.assessment_revision===3));
  await download.saveAs(`${output}/historical-through-23.json`);
  await shot('02-intermediate-historical-dossier');
  await closeDossier();
  pass('Event 23 restores accepted intermediate revision 2; downloaded dossier excludes future revision 3');
  await seek(32);
  assert.equal(await page.locator('.conclusion-text').textContent(),latest.conclusion);
  assert.equal((await page.locator('.conclusion-panel .panel-head .pill').textContent()).trim(),'Revision 3');
  assert.match(await page.locator('.status-axes').textContent(),/incomplete.*unknown.*current/is);
  await page.locator('.conclusion-panel').screenshot({path:`${output}/03-latest-unresolved-result.png`});
  await page.getByRole('button',{name:'Dossier at this commit',exact:true}).click();
  assert.match(await dossier.locator('.shp-assessments').textContent(),/revision 3/);
  assert.ok((await dossier.locator('.shp-assessments').textContent()).includes(latest.conclusion));
  await closeDossier();
  pass('Terminal replay and dossier preserve failed latest review; workflow completion does not imply accepted science');
  await seek(acceptedSequence);
  assert.equal(await page.locator('.conclusion-text').textContent(),intermediate.conclusion);
  await seek(firstSequence-1);
  assert.equal((await page.locator('.conclusion-panel .panel-head .pill').textContent()).trim(),'Unresolved');
  assert.notEqual(await page.locator('.conclusion-text').textContent(),intermediate.conclusion);
  await page.getByRole('button',{name:'Dossier at this commit',exact:true}).click();
  await dossier.getByText('No assessment has been committed in this record.',{exact:true}).waitFor();
  await closeDossier();
  pass('Repeated backward seeking restores the correct revision and removes all assessments before event 15');
  await page.getByRole('button',{name:/Harness evolution/}).click();
  const harness=page.getByRole('dialog',{name:'Harness evolution'});
  await harness.getByRole('textbox',{name:'Saved experiment ID'}).fill(experimentId);
  await harness.getByRole('button',{name:'Open',exact:true}).click();
  const assigned=harness.getByRole('table',{name:'Live assigned case results'});
  const row=assigned.getByRole('row').filter({has:page.locator(`a[href="/?run=${runId}"]`)});
  await row.waitFor();
  const savedCase=experiment.results.find(result=>result.run_id===runId);
  assert.equal(savedCase.score.completed,false);assert.equal(savedCase.score.support_ok,false);
  assert.ok((await row.textContent()).includes(`${savedCase.score.required_correct} / ${savedCase.score.required_total}`));
  assert.ok((await row.textContent()).includes('Incomplete · support failed'));
  if(experiment.promotion?.status==='rejected')assert.match(await harness.locator('.proposal-selection').textContent(),/rejected/i);
  await row.scrollIntoViewIfNeeded();await page.screenshot({path:`${output}/04-actual-evaluation-status.png`});
  pass('Saved experiment distinguishes correct required outputs from failed support/completion',{required_correct:savedCase.score.required_correct,required_total:savedCase.score.required_total,support_ok:false,completed:false,promotion_status:experiment.promotion?.status??null});
  const after=await get(`/runs/${runId}/export`);
  assert.deepEqual(after.snapshot,before.snapshot);assert.deepEqual(after.events,before.events);
  assert.deepEqual(errors,[]);assert.deepEqual(writes,[]);
  pass('Read-only verification leaves committed state unchanged and makes no model calls');
  const report={passed:true,mode:'recorded_replay_of_real_model_H1',run_id:runId,url:`${base}/?run=${runId}`,experiment_id:experimentId,harness_hash:snapshot.run.harness_hash,observed_experiment_status:experiment.status,observed_promotion:experiment.promotion??null,through_sequence:32,viewport:'1280x720',assessment_commits:[15,23,27],recorded_start:before.events[0].occurred_at,recorded_end:before.events.at(-1).occurred_at,data_version:snapshot.run.data_version,actual_run_usage:snapshot.run.budget,model_calls_by_verification:0,ledger_writes:0,checks,browser_errors:errors,limitations:['This verifies actual changed execution and truthful historical views, not model quality, promotion or improvement.','The latest candidate assessment is unresolved after schema validation failure; an earlier accepted revision is historical only.','Comparison and selection must be read from the experiment, independently of this replay cursor.','The separate Pansio R0 preflight is not a paired comparator for this Olonne validation case.']};
  await writeFile(`${output}/report.json`,JSON.stringify(report,null,2)+'\n');
  console.log(JSON.stringify({passed:true,checks:checks.length,report:`${output}/report.json`}));
} catch(error) {
  await page.screenshot({path:`${output}/failure.png`}).catch(()=>{});
  await writeFile(`${output}/report.json`,JSON.stringify({passed:false,run_id:runId,checks,error:String(error.stack??error),errors,writes},null,2)+'\n');
  throw error;
} finally {await browser.close();}
