// Read-only E2E of the saved genuine R0 baseline segment; never dispatches work.
import {chromium} from '../../frontend/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {mkdir, readFile, writeFile} from 'node:fs/promises';

const base = process.env.SAFE_HARBOR_UI_URL ?? 'http://127.0.0.1:5176';
const runId = 'run-1c38545496844fcb858df0892a3df064';
const output = 'artifacts/safe_harbor/baseline-replay';
const get = async path => {const response = await fetch(`${base}/api${path}`); assert.ok(response.ok); return response.json();};
const before = await get(`/runs/${runId}/export`), snapshot = before.snapshot;
assert.equal(snapshot.run.mode, 'real_model'); assert.equal(snapshot.run.status, 'complete');
const candidate = snapshot.candidates.find(c => c.candidate_id === 'pansio-1');
const reference = snapshot.artifacts.find(a => a.kind === 'reference_assets' && a.data.candidate_id === candidate.candidate_id);
const {sequence: seq, annotation} = reference.data.reference_assets;
assert.equal(createHash('sha256').update(seq.sequence).digest('hex'), seq.sha256);
assert.equal(seq.sequence.length, seq.end - seq.start);
const source = JSON.parse(await readFile('data/safe_harbor/normalized/reference_assets.json', 'utf8'));
assert.equal(source[candidate.candidate_id].sequence.sha256, seq.sha256);
const catalog = await get('/catalog');
const chromosomeLength = catalog.chromosomes.find(c => c.chromosome === candidate.chromosome).length;
const firstAssessment = before.events.find(e => e.upserts.assessments?.length).sequence;
assert.equal(firstAssessment, 9);
const assessment = snapshot.assessments[0];
const checks = [], errors = [], writes = [];
const pass = (check, details = {}) => checks.push({check, passed: true, ...details});
const near = (a, b) => assert.ok(Math.abs(a-b) < 0.000001, `${a} != ${b}`);
await mkdir(output, {recursive: true});
const browser = await chromium.launch({headless: true});
const page = await browser.newPage({viewport: {width: 1280, height: 720}, reducedMotion: 'reduce'});
page.on('pageerror', error => errors.push(error.message));
page.on('request', request => {if (!['GET','HEAD'].includes(request.method())) writes.push(`${request.method()} ${request.url()}`);});
const genome = page.getByRole('region', {name:'Genome viewer'});
const zoom = page.getByRole('navigation', {name:'Genome zoom'});
const slider = page.getByRole('slider', {name:'Replay event position'});
const dossier = page.getByRole('dialog', {name:`Run ${runId}`});
const seek = async sequence => {await slider.fill(String(sequence)); await page.locator('.sequence-count').filter({hasText:`${sequence} / ${snapshot.through_sequence}`}).waitFor();};
const shot = async name => {await page.evaluate(() => window.scrollTo(0,0)); await page.screenshot({path:`${output}/${name}.png`});};
try {
  await page.goto(`${base}/?run=${runId}`);
  await page.locator('.mode-word').getByText('REAL MODEL', {exact:true}).waitFor();
  assert.equal(await page.locator('.conclusion-text').textContent(), assessment.conclusion);
  // This selector controls a possible future run, not the opened record; align it for the recording.
  await page.getByRole('combobox', {name:'Investigation execution mode'}).selectOption('real_model');
  await page.getByRole('button', {name:'Presentation', exact:true}).click();
  await page.locator('.shp-preload.ready').waitFor();
  await page.getByRole('button', {name:'Reset presentation to start'}).click();
  assert.equal(await page.getByRole('button', {name:'Dossier at this commit', exact:true}).isDisabled(), true);
  assert.equal(await page.locator('.mode-word').textContent(), 'CATALOG PREVIEW');
  assert.notEqual(await page.locator('.conclusion-text').textContent(), assessment.conclusion);
  pass('Before event 1 there is no assessment or historical dossier');
  await page.getByRole('checkbox', {name:'Follow camera'}).uncheck();
  await seek(1);
  assert.match(await genome.locator('.reference-availability').textContent(), /Frozen run assets/);
  assert.equal(await page.locator('.data-version').textContent(), snapshot.run.data_version);
  assert.equal((await page.locator('.contextbar .pill').textContent()).trim(), 'RECORDED');
  await zoom.getByRole('button', {name:'Genome', exact:true}).click();
  const marker = genome.getByRole('button', {name:`Select ${candidate.name}`});
  const pos = await marker.evaluate(node => {const row=node.parentElement,bar=row.querySelector('rect'),dot=node.querySelector('circle');return {x:+bar.getAttribute('x'),w:+bar.getAttribute('width'),cx:+dot.getAttribute('cx')};});
  near((pos.cx-pos.x)/pos.w, candidate.start/chromosomeLength);
  assert.equal(await marker.getAttribute('aria-pressed'), 'true');
  pass('Genome marker uses actual coordinate/chromosome length', {chromosome_length:chromosomeLength, start:candidate.start});
  await shot('01-recorded-overview');
  await zoom.getByRole('button', {name:candidate.chromosome, exact:true}).click();
  const x = await genome.locator('g.marker line').evaluate(line=>+line.getAttribute('x1'));
  near((x-35)/860,candidate.start/chromosomeLength);
  pass('Chromosome zoom preserves Pansio-1 coordinate');
  await zoom.getByRole('button', {name:'Locus', exact:true}).click();
  const names = new Set(annotation.features.flatMap(f=>[f.name,f.gene_id]).filter(Boolean));
  for (const name of await genome.locator('.svg-gene').allTextContents()) assert.ok(names.has(name.replace(/ [←→]$/,'')));
  assert.ok((await genome.locator('.coordinate-footer').textContent()).includes(`[${candidate.start}, ${candidate.end})`));
  pass('Locus uses the frozen GENCODE v36 annotation window', {reference_artifact_id:reference.artifact_id});
  await shot('02-frozen-locus');
  await zoom.getByRole('button', {name:'Sequence', exact:true}).click();
  const sequenceStart = candidate.start-20;
  const displayed = await genome.locator('.sequence-row code').evaluateAll(rows=>rows.flatMap(row=>[...row.children].map(span=>({base:span.textContent,title:span.getAttribute('title')}))));
  assert.equal(displayed.map(x=>x.base).join(''),seq.sequence.slice(sequenceStart-seq.start,sequenceStart-seq.start+100).toUpperCase());
  for (const [i,base] of displayed.entries()) assert.equal(base.title,`${candidate.chromosome}:${(sequenceStart+i+1).toLocaleString('en-US')}`);
  assert.match(await genome.locator('.hash-line').textContent(),new RegExp(seq.sha256));
  pass('Sequence displays exact stored bases at original genomic offsets', {sha256:seq.sha256,displayed_start_zero_based:sequenceStart,bases:displayed.length});
  await shot('03-actual-reference-bases');
  await seek(10);
  await zoom.getByRole('button', {name:'Locus', exact:true}).click();
  assert.equal(await page.locator('.conclusion-text').textContent(),assessment.conclusion);
  assert.match(await page.locator('.status-axes').textContent(),/incomplete.*unknown.*current/is);
  pass('Final recorded assessment equals the committed real-model answer', {assessment_id:assessment.assessment_id});
  await shot('04-recorded-baseline-answer');
  await page.getByRole('button', {name:'Dossier at this commit', exact:true}).click();
  assert.equal(await dossier.locator('.shp-assessments article').count(),1);
  assert.equal(await dossier.locator('.shp-checks .bad').count(),0);
  await dossier.getByRole('button', {name:'Close dossier', exact:true}).last().click();
  await seek(firstAssessment-1);
  assert.notEqual(await page.locator('.conclusion-text').textContent(),assessment.conclusion);
  assert.equal((await page.locator('.conclusion-panel .panel-head .pill').textContent()).trim(),'Unresolved');
  pass('Backward seek to event 8 removes the future assessment');
  await seek(1);
  await page.getByRole('button', {name:'Dossier at this commit', exact:true}).click();
  await dossier.getByText('No assessment has been committed in this record.', {exact:true}).waitFor();
  assert.equal(await dossier.locator('.shp-checks .bad').count(),0);
  const downloading = page.waitForEvent('download');
  await dossier.getByRole('button',{name:'Download dossier JSON ↓',exact:true}).click();
  const download = await downloading;
  const historical = JSON.parse(await readFile(await download.path(),'utf8'));
  assert.equal(historical.snapshot.through_sequence,1); assert.equal(historical.snapshot.assessments.length,0);
  assert.equal(historical.immutable_assessment_revisions.length,0); assert.ok(historical.events.every(e=>e.sequence<=1));
  assert.equal(historical.reference_assets[0].artifact_id,reference.artifact_id);
  await download.saveAs(`${output}/historical-through-1.json`);
  pass('Historical dossier download contains only event-1 state and reference assets');
  await shot('05-historical-dossier');
  await dossier.getByRole('button', {name:'Close dossier',exact:true}).last().click();
  await page.getByRole('button', {name:'Reset presentation to start'}).click();
  await page.getByRole('combobox', {name:'Replay speed'}).selectOption('4');
  await page.getByRole('button', {name:'Play presentation replay'}).click();
  await page.waitForFunction(() => document.querySelector('.sequence-count')?.textContent==='10 / 10');
  assert.equal(await page.locator('.conclusion-text').textContent(),assessment.conclusion);
  pass('Recorded playback reaches the stored final answer at 4 events per second');
  const after = await get(`/runs/${runId}/export`);
  assert.deepEqual(after.events,before.events); assert.deepEqual(after.snapshot,before.snapshot);
  assert.deepEqual(errors,[]); assert.deepEqual(writes,[]);
  pass('Inspection issues no writes and leaves the authoritative record unchanged');
  const report={passed:true,segment:'Completed genuine R0 baseline; not canonical Q11 or an improvement comparison',run_id:runId,url:`${base}/?run=${runId}`,mode:'recorded_replay_of_real_model',model_calls_by_this_journey:0,ledger_writes:0,viewport:'1280x720',data_version:snapshot.run.data_version,through_sequence:snapshot.through_sequence,first_assessment_sequence:firstAssessment,recorded_start:before.events[0].occurred_at,recorded_end:before.events.at(-1).occurred_at,actual_run_usage:snapshot.run.budget,checks,browser_errors:errors,limitations:['R0 ran every relevant deterministic analysis before one synthesis call; this does not demonstrate adaptive tool selection.','No evidence revision or process interruption occurs in this specific run. Those are separate operational recordings.','No automatic executable H1 or successful comparison is established by this segment.','Playback uses event count, not elapsed scientific execution time.']};
  await writeFile(`${output}/report.json`,JSON.stringify(report,null,2)+'\n');
  console.log(JSON.stringify({passed:true,checks:checks.length,report:`${output}/report.json`}));
} catch(error) {
  await page.screenshot({path:`${output}/failure.png`}).catch(()=>{});
  await writeFile(`${output}/report.json`,JSON.stringify({passed:false,run_id:runId,checks,error:String(error?.stack??error),browser_errors:errors,writes},null,2)+'\n');
  throw error;
} finally {await browser.close();}
