// GET-only inspection of the selected H0 run's separate final-report summary.
import {chromium} from '../../frontend/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const base=process.env.SAFE_HARBOR_UI_URL??'http://127.0.0.1:5176';
const runId='run-0142454a0a6b4976bd380c6eeeddec99';
const output='artifacts/safe_harbor/final-dossier-replay';
const get=async path=>{const r=await fetch(`${base}/api${path}`);assert.ok(r.ok);return r.json();};
const before=await get(`/runs/${runId}/export`),state=before.snapshot;
const artifact=state.artifacts.find(a=>a.kind==='versioned_dossier');
const summary=artifact.data.validated_summary;
const assessment=[...state.assessments].sort((a,b)=>b.assessment_revision-a.assessment_revision)[0];
const commit=before.events.find(e=>e.upserts.artifacts?.some(a=>a.artifact_id===artifact.artifact_id)).sequence;
assert.equal(commit,27);assert.equal(summary.assessment_revision,3);assert.equal(summary.model_proposal_accepted,true);
assert.equal(assessment.assessment_revision,2);assert.equal(assessment.model_proposal_accepted,false);
const producer=state.tasks.find(t=>t.task_id===artifact.provenance.task_id);
assert.equal(producer.status,'complete');assert.ok(producer.result_artifact_ids.includes(artifact.artifact_id));
for(const read of [...artifact.input_read_set,...summary.input_read_set])assert.equal(state.run.evidence_versions[read.key],read.version);
await mkdir(output,{recursive:true});
const checks=[],errors=[],writes=[];const pass=(check,details={})=>checks.push({check,passed:true,...details});
const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1280,height:720},reducedMotion:'reduce'});
page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!['GET','HEAD'].includes(r.method()))writes.push(r.method()+' '+r.url());});
const card=page.getByRole('region',{name:'Stored final dossier summary'});
const menu=page.locator('details.more-menu');
const revealMenu=async()=>{if(await menu.count()&&!await menu.evaluate(node=>node.open))await menu.locator('summary').click();};
const seek=async n=>{await page.getByRole('slider',{name:'Replay event position'}).fill(String(n));await page.waitForFunction(n=>document.querySelector('.sequence-count')?.textContent?.startsWith(`${n} / `),n);};
try {
  await page.goto(`${base}/?run=${runId}`);await card.waitFor();
  assert.equal(await card.getAttribute('data-current'),'true');assert.equal(await card.getAttribute('data-accepted'),'true');
  assert.equal(await card.locator('.final-dossier-conclusion').textContent(),summary.conclusion);
  assert.equal(await page.locator('.conclusion-panel .conclusion-text').textContent(),assessment.conclusion);
  assert.match(await card.locator('.final-dossier-stage').textContent(),/Earlier assessment stage remains revision 2 · proposal rejected \/ unresolved/);
  pass('Separate final dossier shows the exact accepted revision 3 while earlier rejected assessment revision 2 remains visible');
  await card.getByRole('button',{name:'Inspect exact final dossier artifact',exact:true}).click();
  const inspector=page.getByRole('dialog',{name:'Evidence inspection'});
  assert.equal(await inspector.locator('.artifact-id').textContent(),artifact.artifact_id);
  await inspector.getByText('Exact inputs / numerical result',{exact:true}).click();
  const saved=JSON.parse(await inspector.locator('.raw-record[open] pre').textContent());assert.deepEqual(saved.validated_summary,summary);
  await inspector.getByRole('button',{name:'Close evidence inspector'}).click();
  pass('Final summary opens its exact immutable source artifact, including the stored validation result');
  await revealMenu();await page.getByRole('button',{name:'Presentation',exact:true}).click();
  await page.locator('.shp-preload.ready').waitFor();
  await page.getByRole('button',{name:'Reset presentation to start'}).click();
  assert.equal(await card.count(),0);
  await page.getByRole('checkbox',{name:'Follow camera'}).uncheck();
  await seek(commit-1);assert.equal(await card.count(),0);
  assert.equal(await page.locator('.conclusion-panel .conclusion-text').textContent(),assessment.conclusion);
  await page.locator('.conclusion-panel').screenshot({path:`${output}/01-before-report-commit.png`});
  pass('Before dossier commit 27, no final summary leaks into replay; the prior unresolved assessment remains');
  await seek(commit);await card.waitFor();
  assert.equal(await card.getAttribute('data-current'),'true');assert.equal(await card.getAttribute('data-artifact-id'),artifact.artifact_id);
  assert.equal(await card.locator('.final-dossier-conclusion').textContent(),summary.conclusion);
  assert.equal(await page.locator('.conclusion-panel .conclusion-text').textContent(),assessment.conclusion);
  const axes=await card.locator('.status-axes strong').allTextContents();assert.deepEqual(axes,[summary.screen_status,summary.evidence_status,summary.freshness]);
  await card.screenshot({path:`${output}/02-separate-accepted-dossier.png`});
  pass('Commit 27 displays only the stored report-stage conclusion and axes with current producer/readset gating',{artifact_id:artifact.artifact_id,readset_entries:artifact.input_read_set.length,summary_readset_entries:summary.input_read_set.length});
  await seek(commit-1);assert.equal(await card.count(),0);
  await seek(commit);assert.equal(await card.locator('.final-dossier-conclusion').textContent(),summary.conclusion);
  pass('Repeated backward/forward seeks add and remove the final summary deterministically');
  const after=await get(`/runs/${runId}/export`);
  assert.deepEqual(after.events.filter(e=>e.sequence<=before.through_sequence),before.events);
  assert.deepEqual(after.snapshot.artifacts.find(a=>a.artifact_id===artifact.artifact_id),artifact);
  assert.deepEqual(errors,[]);assert.deepEqual(writes,[]);
  pass('No model calls or ledger writes; a later independent comparison-report attachment is allowed without rewriting history');
  await writeFile(`${output}/report.json`,JSON.stringify({passed:true,run_id:runId,mode:'recorded_replay_of_genuine_selected_H0',url:`${base}/?run=${runId}`,observed_watermark:before.through_sequence,dossier_commit:commit,latest_assessment_revision:2,latest_assessment_accepted:false,final_summary_revision:3,final_summary_accepted:true,artifact_id:artifact.artifact_id,checks,browser_errors:errors,model_calls:0,ledger_writes:0,limitations:['Accepted proposal means stored schema/evidence validation, not biological safety.','The report-stage summary is a separate artifact; no backend assessment pointer was rewritten.','This journey verifies before/after publication and current readset agreement; it does not create a new evidence revision.']},null,2)+'\n');
  console.log(JSON.stringify({passed:true,checks:checks.length,report:`${output}/report.json`}));
} catch(error){await page.screenshot({path:`${output}/failure.png`}).catch(()=>{});await writeFile(`${output}/report.json`,JSON.stringify({passed:false,checks,error:String(error.stack??error),errors,writes},null,2)+'\n');throw error;}finally{await browser.close();}
