import { useState } from 'react';
import type { Artifact, Candidate, Catalog } from '../../../shared/contracts';
export type Zoom = 'genome'|'chromosome'|'locus'|'sequence';
interface Feature {start:number;end:number;name?:string;gene_id?:string;strand?:string;transcript_id?:string}
interface ReferenceAsset {sequence?:{chromosome:string;start:number;end:number;sequence:string;sha256?:string};annotation?:{features:Feature[];coverage:{start:number;end:number;complete:boolean};release:string}}
export function formatInterval(candidate:Candidate){return `${candidate.chromosome}:${(candidate.start+1).toLocaleString()}–${candidate.end.toLocaleString()}`;}
export function Genome({catalog,candidates,selected,onSelect,zoom,setZoom,artifacts,dataVersion,previewOnly=false}:{catalog:Catalog|null;candidates:Candidate[];selected?:Candidate;onSelect:(id:string)=>void;zoom:Zoom;setZoom:(value:Zoom)=>void;artifacts:Artifact[];dataVersion?:string;previewOnly?:boolean}) {
  const [offset,setOffset]=useState(0);
  const catalogVersionMatches=dataVersion===undefined||catalog?.data_version===dataVersion;
  const assets=(!previewOnly&&catalogVersionMatches?catalog?.reference_assets??{}:{}) as Record<string,ReferenceAsset>;
  let reference=selected?assets[selected.candidate_id]:undefined;
  // Only artifacts present at this reconstructed watermark can supply historical tracks.
  const frozenReference=artifacts.filter(a=>a.kind==='reference_assets'&&a.data.candidate_id===selected?.candidate_id&&a.data.data_version===dataVersion).sort((a,b)=>a.revision-b.revision).at(-1);
  if(frozenReference&&!previewOnly)reference=frozenReference.data.reference_assets as ReferenceAsset;
  const sequenceArtifact=artifacts.filter(a=>a.kind==='reference_sequence'&&a.data.candidate_id===selected?.candidate_id&&a.data.data_version===dataVersion).sort((a,b)=>a.revision-b.revision).at(-1);
  if(sequenceArtifact&&!previewOnly)reference={...reference,sequence:sequenceArtifact.data as unknown as ReferenceAsset['sequence']};
  const referenceNotice=previewOnly?'No historical reference evidence at this position. Candidate markers are a neutral preview of the current catalog.':!catalogVersionMatches&&!frozenReference?`Reference assets for ${dataVersion} are unavailable in this stored record. The current catalog is a different version; its annotations and bases are not shown.`:frozenReference?`Frozen run assets · ${String(frozenReference.data.data_version)}`:dataVersion?`Version-matched catalog assets · ${dataVersion}`:'Current catalog preview · no investigation assessment';
  const seq=reference?.sequence, annotation=reference?.annotation;
  const chromosomes=catalog?.chromosomes??[];
  const length=chromosomes.find(chr=>chr.chromosome===selected?.chromosome)?.length;
  const features=annotation?.features??[];
  const start=Math.max(annotation?.coverage.start??0,(selected?.start??0)-100000),end=Math.min(annotation?.coverage.end??Number.MAX_SAFE_INTEGER,(selected?.end??0)+100000);
  const displayedFeatures=features.filter(feature=>feature.end>start&&feature.start<end);
  const geneFeatures=new Map<string,Feature>();
  for(const feature of displayedFeatures){const key=feature.gene_id??feature.name??feature.transcript_id??String(feature.start);const existing=geneFeatures.get(key);geneFeatures.set(key,existing?{...existing,start:Math.min(existing.start,feature.start),end:Math.max(existing.end,feature.end)}:feature);}
  const uniqueFeatures=[...geneFeatures.values()].sort((a,b)=>Math.min(Math.abs(a.start-(selected?.start??0)),Math.abs(a.end-(selected?.end??0)))-Math.min(Math.abs(b.start-(selected?.start??0)),Math.abs(b.end-(selected?.end??0))));
  const px=(value:number)=>45+((value-start)/(end-start))*850;
  const sequenceStart=seq?Math.max(seq.start,Math.min((selected?.start??seq.start)-20+offset,seq.end-1)):0;
  const bases=seq?.sequence.slice(sequenceStart-seq.start,sequenceStart-seq.start+100)??'';
  return <section className="panel genome-panel" aria-label="Genome viewer"><div className="panel-head"><div><span className="eyebrow">Reference coordinates</span><h2>{zoom==='genome'?'The published shortlist':selected?.name??'Choose a candidate'}</h2></div><span className="small muted">GRCh38 · reference + strand</span></div>
    <nav className="genome-breadcrumb" aria-label="Genome zoom">{(['genome','chromosome','locus','sequence'] as Zoom[]).map((level,index)=><span key={level}><button disabled={level!=='genome'&&!selected} className={zoom===level?'active':''} onClick={()=>{setOffset(0);setZoom(level);}}>{['Genome',selected?.chromosome??'Chromosome','Locus','Sequence'][index]}</button>{index<3&&<span className="crumb-separator">›</span>}</span>)}</nav>
    <div className="reference-availability" role="status">{referenceNotice}</div>
    <div className={`genome-canvas zoom-${zoom}`} key={`${zoom}-${selected?.candidate_id}`}>
    {zoom==='genome'&&<>{chromosomes.length?<svg role="img" aria-label="Human GRCh38 chromosomes with publication-derived candidate markers" viewBox="0 0 930 250">{chromosomes.filter(c=>c.chromosome!=='chrM').map((chr,index)=>{const row=index%12,col=Math.floor(index/12),x=col*465+50,y=row*19+13,w=chr.length/Math.max(...chromosomes.map(c=>c.length))*375;return <g key={chr.chromosome}><text x={x-11} y={y+8} textAnchor="end" className="svg-label">{chr.chromosome.replace('chr','')}</text><rect x={x} y={y} width={w} height={10} rx={5} fill="#27374d"/>{candidates.filter(c=>c.chromosome===chr.chromosome).map(c=><g key={c.candidate_id} role="button" tabIndex={0} aria-label={`Select ${c.name}`} onClick={()=>onSelect(c.candidate_id)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();onSelect(c.candidate_id);}}} className="marker"><title>{c.name} · {formatInterval(c)}</title><circle cx={x+c.start/chr.length*w} cy={y+5} r={c.candidate_id===selected?.candidate_id?7:5} fill={c.candidate_id===selected?.candidate_id?'#7ee8dd':'#dcae67'} stroke="#101c2e" strokeWidth={2}/></g>)}</g>;})}</svg>:<div className="empty-state">Verified chromosome lengths are loading with the source catalog.</div>}<div className="genome-footnote"><span><i className="dot cyan"/> Published candidates at actual positions</span><span>Neutral regions have not been investigated</span></div></>}
    {zoom==='chromosome'&&selected&&<><div className="chromosome-title"><strong>{selected.chromosome}</strong><span>{length?.toLocaleString()??'Unknown'} reference bases</span></div>{length?<svg viewBox="0 0 930 145" role="img" aria-label={`${selected.chromosome}, selected candidate at ${selected.start}`}><rect x={35} y={55} width={860} height={28} rx={14} fill="#2b3c54"/>{candidates.filter(c=>c.chromosome===selected.chromosome).map(c=><g key={c.candidate_id} className="marker" onClick={()=>onSelect(c.candidate_id)}><line x1={35+c.start/length*860} x2={35+c.start/length*860} y1={40} y2={96} stroke="#7ee8dd" strokeWidth={4}/><text x={35+c.start/length*860} y={25} textAnchor="middle" className="svg-label">{c.name}</text></g>)}<text x={35} y={120} className="svg-label">1</text><text x={895} y={120} textAnchor="end" className="svg-label">{length.toLocaleString()}</text></svg>:<p>Chromosome length unavailable.</p>}<button className="text-button" onClick={()=>setZoom('locus')}>Inspect selected locus →</button></>}
    {zoom==='locus'&&selected&&<><div className="track-heading"><span>{annotation?.release??'Annotations unavailable'}</span><span>{annotation?.coverage.complete?'Complete coverage of displayed window':'Coverage not verified'}</span></div><svg viewBox="0 0 940 215" role="img" aria-label={`Coordinate-correct annotation view for ${formatInterval(selected)}`}><line x1={45} x2={895} y1={40} y2={40} stroke="#40546c"/>{Array.from({length:5},(_,i)=>{const pos=start+(end-start)*i/4;return <g key={i}><line x1={px(pos)} x2={px(pos)} y1={35} y2={190} stroke="#22334a"/><text x={px(pos)} y={24} textAnchor="middle" className="svg-label">{Math.round(pos+1).toLocaleString()}</text></g>;})}<rect x={px(selected.start)} width={Math.max(2,px(selected.end)-px(selected.start))} y={42} height={142} fill="#6cdbcc22" stroke="#7ee8dd"/><text x={px(selected.start)+5} y={62} className="svg-label accent-text">{selected.name}</text>{uniqueFeatures.slice(0,12).map((f,i)=><g key={`${f.gene_id}-${i}`}><rect x={px(Math.max(start,f.start))} width={Math.max(2,px(Math.min(end,f.end))-px(Math.max(start,f.start)))} y={82+(i%4)*26} height={7} rx={2} fill="#9daec7"/><text x={Math.min(800,px(Math.max(start,f.start)))} y={78+(i%4)*26} className="svg-gene">{f.name??f.gene_id} {f.strand==='-'?'←':'→'}</text></g>)}</svg>{!displayedFeatures.length&&<p className="muted">{annotation?.coverage.complete?'No annotations in this covered window.':'No frozen annotation window available yet.'}</p>}<div className="genome-footnote"><span>SVG reference viewer · merged gene spans, not exon models</span><span>{uniqueFeatures.length} genes{uniqueFeatures.length>12?' · 12 nearest spans shown':''}</span></div><button className="text-button" onClick={()=>setZoom('sequence')}>Read frozen reference bases →</button></>}
    {zoom==='sequence'&&<>{seq&&selected?<><div className="track-heading"><span>{seq.chromosome}:{(sequenceStart+1).toLocaleString()}–{(sequenceStart+bases.length).toLocaleString()}</span><span>GRCh38 · {bases.length} actual reference bases</span></div><div className="sequence-strip" aria-label="Actual reference sequence">{[0,50].map(row=>bases.slice(row,row+50).length>0&&<div className="sequence-row" key={row}><span className="sequence-label">{(sequenceStart+row+1).toLocaleString()}</span><code>{[...bases.slice(row,row+50)].map((base,i)=><span className={`${sequenceStart+row+i>=selected.start&&sequenceStart+row+i<selected.end?'inside-candidate':''} base-${base.toUpperCase()}`} title={`${seq.chromosome}:${(sequenceStart+row+i+1).toLocaleString()}`} key={i}>{base.toUpperCase()}</span>)}</code></div>)}</div><div className="sequence-controls"><button onClick={()=>setOffset(value=>value-50)} disabled={sequenceStart<=seq.start}>← 50 bp</button><button onClick={()=>setOffset(value=>value+50)} disabled={sequenceStart+bases.length>=seq.end}>50 bp →</button><span className="muted">Frozen window: {(seq.start+1).toLocaleString()}–{seq.end.toLocaleString()}</span></div><div className="genome-footnote">Highlighted bases fall inside the published candidate interval. Reference sequence is not a personalized H1 genome. Source letter case is normalized to uppercase for display.</div>{seq.sha256&&<div className="hash-line">SHA-256 {seq.sha256}</div>}</>:<div className="empty-state">Actual reference bases are unavailable for this record. No sequence is inferred.</div>}</>}
    </div>{selected&&<div className="coordinate-footer"><span className="coordinate-value">{formatInterval(selected)}</span><span>Display: 1-based inclusive · stored: [{selected.start}, {selected.end})</span></div>}
  </section>;
}
