import { useMemo, useRef, useState } from 'react';
import { Background, ReactFlow, Handle, Position, type NodeProps, type Node, type Edge } from '@xyflow/react';
import type { Artifact, Task } from '../../../shared/contracts';
const stage = {screen_regions:0,inspect_evidence:1,compute_features:2,assess_candidate:3,review_candidate:3,publish_shortlist:4};
export const taskName = {screen_regions:'Screen criteria',inspect_evidence:'Inspect evidence',compute_features:'Compare measurements',assess_candidate:'Assess candidate',review_candidate:'Review assessment',publish_shortlist:'Publish dossier'};
const statusIcon:Record<string,string>={queued:'○',running:'◌',complete:'✓',blocked:'!',reopened:'↻',superseded:'↗',failed:'!'};
function TaskNode({data}:NodeProps<Node<{task:Task;selected:boolean}>>) {const task=data.task;return <div className={`task-node ${task.status} ${data.selected?'selected':''}`}><Handle type="target" position={Position.Left}/><span className={`task-state ${task.status}`}>{statusIcon[task.status]} {task.status}</span><strong>{taskName[task.kind]}</strong><span className="task-question">{task.question}</span>{task.reopen_reason&&<span className="task-reopen">↻ {task.reopen_reason}</span>}<span className="task-role">{task.candidate_id??'All candidates'} · {task.role_id}</span><Handle type="source" position={Position.Right}/></div>;}
const nodeTypes={task:TaskNode};
export function Graph({tasks,artifacts,selected,candidateId,onSelect}:{tasks:Task[];artifacts:Artifact[];selected?:string;candidateId?:string;onSelect:(task:Task)=>void}){
 const [showAll,setShowAll]=useState(false);const placements=useRef(new Map<string,number>());const placementRun=useRef('');
 const visibleTasks=useMemo(()=>{if(showAll||!candidateId)return tasks;const selectedIds=new Set(tasks.filter(task=>task.candidate_id===candidateId||!task.candidate_id).map(task=>task.task_id));let changed=true;while(changed){changed=false;for(const task of tasks.filter(t=>selectedIds.has(t.task_id)))for(const parent of task.depends_on)if(!selectedIds.has(parent)){selectedIds.add(parent);changed=true;}}return tasks.filter(task=>selectedIds.has(task.task_id));},[tasks,candidateId,showAll]);
 const {nodes,edges}=useMemo(()=>{const viewKey=`${tasks[0]?.run_id??''}:${showAll?'all':candidateId}`;if(placementRun.current!==viewKey){placements.current.clear();placementRun.current=viewKey;}const rows=[0,0,0,0,0];for(const task of visibleTasks){const row=placements.current.get(task.task_id);if(row!==undefined)rows[stage[task.kind]]=Math.max(rows[stage[task.kind]],row+1);}const sorted=[...visibleTasks].sort((a,b)=>stage[a.kind]-stage[b.kind] || a.task_id.localeCompare(b.task_id));const nodes:Node[] = sorted.map(task=>{let row=placements.current.get(task.task_id);if(row===undefined){row=rows[stage[task.kind]]++;placements.current.set(task.task_id,row);}return {id:task.task_id,type:'task',position:{x:stage[task.kind]*264,y:row*172},data:{task,selected:selected===task.task_id}};});const edges:Edge[]=visibleTasks.flatMap(task=>task.depends_on.filter(id=>visibleTasks.some(other=>other.task_id===id)).map(id=>({id:`${id}:${task.task_id}`,source:id,target:task.task_id,type:'smoothstep',animated:task.status==='running',style:{stroke:task.status==='reopened'?'#e6b771':'#51627d',strokeWidth:1.3},label:task.status==='reopened'?'reopened':undefined})));return{nodes,edges};},[tasks,visibleTasks,selected,candidateId,showAll]);
 const shared=artifacts.filter(a=>tasks.filter(t=>t.input_read_set.some(r=>r.key===a.artifact_id)).length>1);
 return <section className="panel graph-panel" aria-label="Investigation graph"><div className="panel-head"><div><span className="eyebrow">An inspectable investigation</span><h2>Follow the work</h2></div><div className="graph-view-toggle"><span className="small muted">{visibleTasks.filter(t=>t.status==='complete').length} / {visibleTasks.length} tasks complete</span><button onClick={()=>setShowAll(value=>!value)} aria-pressed={showAll}>{showAll?'Selected candidate':'All candidates'}</button></div></div><div className="stage-labels">{['Screen','Investigate','Compare','Review','Report'].map((text,index)=><span key={text}><i>{index+1}</i>{text}</span>)}</div><div className="flow-canvas">{visibleTasks.length?<ReactFlow key={`${showAll}-${candidateId}`} nodes={nodes} edges={edges} nodeTypes={nodeTypes} onNodeClick={(_,node)=>onSelect(node.data.task as Task)} fitView fitViewOptions={{padding:0.08,minZoom:.55,maxZoom:1}} minZoom={.35} maxZoom={1.4} nodesDraggable={false} nodesConnectable={false} elementsSelectable={true} proOptions={{hideAttribution:true}} aria-label="Actual task dependencies"><Background color="#26354b" gap={22} size={1}/></ReactFlow>:<div className="empty-state">Start an investigation to see its actual tasks and dependencies.<br/><span className="muted">Two workers · bounded tools · saved evidence dependencies</span></div>}</div><div className="graph-footer"><span>○ Queued</span><span>◌ Running</span><span>✓ Complete</span><span>↻ Reopened</span><span>! Blocked</span>{shared.length>0&&<span>{shared.length} shared evidence records</span>}</div></section>;
}
