import { useMemo, useRef, useState } from 'react';
import { Background, ReactFlow, Handle, Position, type NodeProps, type Node, type Edge } from '@xyflow/react';
import type { Artifact, Task } from '../../../shared/contracts';
const stage = {screen_regions:0,inspect_evidence:1,compute_features:2,assess_candidate:3,review_candidate:3,publish_shortlist:4};
export const taskName = {screen_regions:'Screen criteria',inspect_evidence:'Inspect evidence',compute_features:'Compare measurements',assess_candidate:'Assess candidate',review_candidate:'Review assessment',publish_shortlist:'Publish dossier'};
const statusIcon:Record<string,string>={queued:'○',running:'◌',complete:'✓',blocked:'!',reopened:'↻',superseded:'↗',failed:'!'};
const MAX_SHARED_RECORDS=8;
export function consumesArtifact(task:Task,artifact:Artifact){return task.input_read_set.some(read=>read.kind==='artifact'&&(read.key===`artifact:${artifact.artifact_id}`||read.key===artifact.artifact_id)&&(read.version===artifact.content_hash||read.version===artifact.revision));}
function TaskNode({data}:NodeProps<Node<{task:Task;selected:boolean}>>) {const task=data.task;return <div className={`task-node ${task.status} ${data.selected?'selected':''}`}><Handle type="target" position={Position.Left}/><span className={`task-state ${task.status}`}>{statusIcon[task.status]} {task.status}</span><strong>{taskName[task.kind]}</strong><span className="task-question">{task.question}</span>{task.reopen_reason&&<span className="task-reopen">↻ {task.reopen_reason}</span>}<span className="task-role">{task.candidate_id??'All candidates'} · {task.role_id}</span><Handle type="source" position={Position.Right}/></div>;}
function EvidenceNode({data}:NodeProps<Node<{artifact:Artifact;consumerCount:number}>>) {return <div className="shared-evidence-node"><span className="eyebrow">Shared immutable evidence</span><strong>{String(data.artifact.data.tool_name??data.artifact.kind).replaceAll('_',' ')}</strong><span>Revision {data.artifact.revision} · {data.consumerCount} recorded consumers</span><code>{data.artifact.content_hash.slice(0,12)}…</code><Handle type="source" position={Position.Top}/></div>;}
const nodeTypes={task:TaskNode,evidence:EvidenceNode};
export function Graph({tasks,artifacts,selected,candidateId,onSelect,onArtifact}:{tasks:Task[];artifacts:Artifact[];selected?:string;candidateId?:string;onSelect:(task:Task)=>void;onArtifact:(artifact:Artifact)=>void}){
 const [showAll,setShowAll]=useState(false),[showEvidence,setShowEvidence]=useState(false);
 const placements=useRef(new Map<string,number>()),placementRun=useRef('');
 const visibleTasks=useMemo(()=>{if(showAll||!candidateId)return tasks;const selectedIds=new Set(tasks.filter(task=>task.candidate_id===candidateId||!task.candidate_id).map(task=>task.task_id));let changed=true;while(changed){changed=false;for(const task of tasks.filter(t=>selectedIds.has(t.task_id)))for(const parent of task.depends_on)if(!selectedIds.has(parent)){selectedIds.add(parent);changed=true;}}return tasks.filter(task=>selectedIds.has(task.task_id));},[tasks,candidateId,showAll]);
 const shared=useMemo(()=>artifacts.map(artifact=>({artifact,consumers:visibleTasks.filter(task=>consumesArtifact(task,artifact))})).filter(item=>item.consumers.length>1).sort((a,b)=>a.artifact.created_at.localeCompare(b.artifact.created_at)||a.artifact.artifact_id.localeCompare(b.artifact.artifact_id)),[artifacts,visibleTasks]);
 const displayedShared=shared.slice(0,MAX_SHARED_RECORDS);
 const {nodes,edges}=useMemo(()=>{
  const viewKey=`${tasks[0]?.run_id??''}:${showAll?'all':candidateId}`;
  if(placementRun.current!==viewKey){placements.current.clear();placementRun.current=viewKey;}
  const rows=[0,0,0,0,0];
  for(const task of visibleTasks){const row=placements.current.get(task.task_id);if(row!==undefined)rows[stage[task.kind]]=Math.max(rows[stage[task.kind]],row+1);}
  const sorted=[...visibleTasks].sort((a,b)=>stage[a.kind]-stage[b.kind]||a.task_id.localeCompare(b.task_id));
  const nodes:Node[]=sorted.map(task=>{let row=placements.current.get(task.task_id);if(row===undefined){row=rows[stage[task.kind]]++;placements.current.set(task.task_id,row);}return{id:task.task_id,type:'task',position:{x:stage[task.kind]*264,y:row*172},data:{task,selected:selected===task.task_id}};});
  const visibleIds=new Set(visibleTasks.map(task=>task.task_id));
  const edges:Edge[]=visibleTasks.flatMap(task=>task.depends_on.filter(id=>visibleIds.has(id)).map(id=>({id:`${id}:${task.task_id}`,source:id,target:task.task_id,type:'smoothstep',animated:task.status==='running',style:{stroke:task.status==='reopened'?'#e6b771':'#51627d',strokeWidth:1.3},label:task.status==='reopened'?'reopened':undefined})));
  if(showEvidence){
   const evidenceY=Math.max(...rows)*172+60;
   for(const [index,{artifact,consumers}] of shared.slice(0,MAX_SHARED_RECORDS).entries()){
    const id=`evidence:${artifact.artifact_id}`;
    nodes.push({id,type:'evidence',position:{x:(index%5)*264,y:evidenceY+Math.floor(index/5)*140},data:{artifact,consumerCount:consumers.length},ariaLabel:`Shared evidence ${artifact.artifact_id}, ${consumers.length} recorded consumers`});
    for(const consumer of consumers)edges.push({id:`read:${artifact.artifact_id}:${consumer.task_id}`,source:id,target:consumer.task_id,type:'smoothstep',className:'shared-evidence-edge',style:{stroke:'#74b9b2',strokeWidth:1,strokeDasharray:'4 5'},ariaLabel:`Recorded input ${artifact.artifact_id} consumed by ${consumer.task_id}`});
   }
  }
  return{nodes,edges};
 },[tasks,visibleTasks,selected,candidateId,showAll,showEvidence,shared]);
 return <section className="panel graph-panel" aria-label="Investigation graph"><div className="panel-head"><div><span className="eyebrow">An inspectable investigation</span><h2>Follow the work</h2></div><div className="graph-view-toggle"><span className="small muted">{visibleTasks.filter(t=>t.status==='complete').length} / {visibleTasks.length} tasks complete</span><button onClick={()=>setShowAll(value=>!value)} aria-pressed={showAll}>{showAll?'Selected candidate':'All candidates'}</button><button onClick={()=>setShowEvidence(value=>!value)} aria-expanded={showEvidence} aria-controls="shared-evidence-records">{showEvidence?'Hide':'Show'} shared evidence ({shared.length})</button></div></div><div className="stage-labels">{['Screen','Investigate','Compare','Review','Report'].map((text,index)=><span key={text}><i>{index+1}</i>{text}</span>)}</div><div className={`flow-canvas ${showEvidence?'with-evidence':''}`}>{visibleTasks.length?<ReactFlow key={`${showAll}-${candidateId}-${showEvidence}`} nodes={nodes} edges={edges} nodeTypes={nodeTypes} onNodeClick={(_,node)=>node.type==='evidence'?onArtifact(node.data.artifact as Artifact):onSelect(node.data.task as Task)} fitView fitViewOptions={{padding:0.08,minZoom:.45,maxZoom:1}} minZoom={.25} maxZoom={1.4} nodesDraggable={false} nodesConnectable={false} elementsSelectable={true} proOptions={{hideAttribution:true}} aria-label="Actual task and recorded evidence dependencies"><Background color="#26354b" gap={22} size={1}/></ReactFlow>:<div className="empty-state">Start an investigation to see its actual tasks and dependencies.<br/><span className="muted">Two workers · bounded tools · saved evidence dependencies</span></div>}</div>
 {showEvidence&&<div className="shared-evidence-records" id="shared-evidence-records"><p>Dotted connections show exact version-matched artifact reads. Task dependency connections remain solid. Query scopes and source availability are inspectable in each task’s saved read set.</p>{shared.length>MAX_SHARED_RECORDS&&<p className="notice amber">Showing {MAX_SHARED_RECORDS} of {shared.length} shared artifact records to keep the graph readable. The complete read sets remain in task inspection and the export.</p>}{!shared.length&&<p>No artifact version has multiple recorded consumers in this view at this point in the investigation.</p>}{displayedShared.map(({artifact,consumers})=><div className="shared-evidence-record" data-artifact-id={artifact.artifact_id} key={artifact.artifact_id}><button className="shared-artifact-link" onClick={()=>onArtifact(artifact)}><strong>{String(artifact.data.tool_name??artifact.kind).replaceAll('_',' ')}</strong><code>{artifact.artifact_id}</code><span>Revision {artifact.revision} · {artifact.content_hash.slice(0,12)}…</span></button><div className="shared-consumers"><span>Recorded consumers ({consumers.length})</span>{consumers.map(consumer=><button key={consumer.task_id} data-consumer-id={consumer.task_id} onClick={()=>onSelect(consumer)}>{taskName[consumer.kind]} · {consumer.role_id} · {consumer.status}</button>)}</div></div>)}</div>}
 <div className="graph-footer"><span>○ Queued</span><span>◌ Running</span><span>✓ Complete</span><span>↻ Reopened</span><span>! Blocked</span>{shared.length>0&&<span>{shared.length} shared evidence records</span>}</div></section>;
}
