import { useState } from 'react';
import type { Artifact, Assessment, Task } from '../../../shared/contracts';
import { taskName } from './Graph';
export function JsonRecord({value,label='Full record'}:{value:unknown;label?:string}) {return <details className="raw-record"><summary>{label}</summary><pre>{JSON.stringify(value,null,2)}</pre></details>;}
function DataTable({rows}:{rows:Record<string,unknown>[]}) {const columns=[...new Set(rows.flatMap(row=>Object.keys(row)))].slice(0,8);return <div className="table-scroll"><table><thead><tr>{columns.map(key=><th key={key}>{key.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{rows.slice(0,30).map((row,index)=><tr key={index}>{columns.map(key=><td key={key}>{typeof row[key]==='object'?JSON.stringify(row[key]):String(row[key]??'—')}</td>)}</tr>)}</tbody></table>{rows.length>30&&<p className="muted">First 30 of {rows.length} rows. All rows remain in the exact record below.</p>}</div>;}
export function ArtifactCard({artifact}:{artifact:Artifact}) {const calculation=typeof artifact.data.calculation==='object'&&artifact.data.calculation!==null&&!Array.isArray(artifact.data.calculation)?artifact.data.calculation as Record<string,unknown>:{};const values=Object.entries({...artifact.data,...calculation});const metrics=values.filter(([,v])=>typeof v==='number'||typeof v==='boolean'||typeof v==='string'&&String(v).length<150);const tables=values.filter(([,v])=>Array.isArray(v)&&v.length&&typeof v[0]==='object');return <article className="artifact-card"><div className="artifact-heading"><strong>{String(artifact.data.tool_name??artifact.kind).replaceAll('_',' ')}</strong><span>rev {artifact.revision}</span></div><code className="artifact-id">{artifact.artifact_id}</code>{metrics.length>0&&<dl className="metric-grid">{metrics.slice(0,16).map(([key,value])=><div key={key}><dt>{key.replaceAll('_',' ')}</dt><dd>{String(value)}</dd></div>)}</dl>}{tables.map(([key,rows])=><details className="source-table" key={key}><summary>{key.replaceAll('_',' ')} · {(rows as unknown[]).length} rows</summary><DataTable rows={rows as Record<string,unknown>[]}/></details>)}{artifact.evidence_ids.length>0&&<p className="evidence-ids">Evidence: {artifact.evidence_ids.join(' · ')}</p>}<JsonRecord value={artifact.provenance} label="Source, versions & provenance"/><JsonRecord value={artifact.data} label="Exact inputs / numerical result"/><div className="hash-line">SHA-256 {artifact.content_hash}</div></article>;}
export function Inspector({task,artifacts,assessment,onClose}:{task?:Task;artifacts:Artifact[];assessment?:Assessment;onClose:()=>void}) {
 const [tab,setTab]=useState<'evidence'|'task'>('evidence');
 const relevant=task?artifacts.filter(a=>task.result_artifact_ids?.includes(a.artifact_id)||task.input_read_set.some(r=>r.key===a.artifact_id)||a.data.task_id===task.task_id||a.provenance.task_id===task.task_id):artifacts;
 return <aside className="inspector-drawer" role="dialog" aria-modal="true" aria-label="Evidence inspection"><div className="drawer-head"><div><span className="eyebrow">Inspect the committed record</span><h2>{task?taskName[task.kind]:'Evidence & calculations'}</h2></div><button aria-label="Close evidence inspector" onClick={onClose}>×</button></div>{task&&<><p className="drawer-question">{task.question}</p><div className="tabbar"><button className={tab==='evidence'?'active':''} onClick={()=>setTab('evidence')}>Inputs & results</button><button className={tab==='task'?'active':''} onClick={()=>setTab('task')}>Task & dependencies</button></div></>}{tab==='task'&&task?<><dl className="detail-list"><div><dt>Status</dt><dd>{task.status}</dd></div><div><dt>Role</dt><dd>{task.role_id}</dd></div><div><dt>Attempt</dt><dd>{task.attempt}</dd></div><div><dt>Allowed tools</dt><dd>{task.allowed_tools.join(', ')}</dd></div><div><dt>Completion condition</dt><dd>{task.completion_condition}</dd></div></dl>{task.reopen_reason&&<div className="notice amber">Reopened: {task.reopen_reason}</div>}<JsonRecord value={task.input_read_set} label="Consumed evidence & query scopes"/><JsonRecord value={task} label="Exact saved task"/></>:<>{relevant.length?relevant.map(a=><ArtifactCard key={a.artifact_id} artifact={a}/>):<p className="empty-state">No accepted numerical artifact at this point in the record.</p>}{assessment&&<JsonRecord value={assessment} label="Complete versioned assessment"/>}</>}</aside>;
}
